//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareX.ScreenCaptureLib.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShareX.ScreenCaptureLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap arrow_circle {
            get {
                object obj = ResourceManager.GetObject("arrow_circle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap arrow_circle_135_left {
            get {
                object obj = ResourceManager.GetObject("arrow_circle_135_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap arrow_circle_225_left {
            get {
                object obj = ResourceManager.GetObject("arrow_circle_225_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap arrow_circle_double {
            get {
                object obj = ResourceManager.GetObject("arrow_circle_double", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Auto copy image to clipboard 的本地化字符串。
        /// </summary>
        internal static string AutoCopyImageToClipboard {
            get {
                return ResourceManager.GetString("AutoCopyImageToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap balloon_box_left {
            get {
                object obj = ResourceManager.GetObject("balloon_box_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Region capture 的本地化字符串。
        /// </summary>
        internal static string BaseRegionForm_InitializeComponent_Region_capture {
            get {
                return ResourceManager.GetString("BaseRegionForm_InitializeComponent_Region_capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bitrate: 的本地化字符串。
        /// </summary>
        internal static string Bitrate {
            get {
                return ResourceManager.GetString("Bitrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blur 的本地化字符串。
        /// </summary>
        internal static string Blur {
            get {
                return ResourceManager.GetString("Blur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap camcorder__pencil {
            get {
                object obj = ResourceManager.GetObject("camcorder__pencil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap camera {
            get {
                object obj = ResourceManager.GetObject("camera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap CircleNode {
            get {
                object obj = ResourceManager.GetObject("CircleNode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap clipboard {
            get {
                object obj = ResourceManager.GetObject("clipboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] closedhand {
            get {
                object obj = ResourceManager.GetObject("closedhand", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Close (Esc) 的本地化字符串。
        /// </summary>
        internal static string CloseEsc {
            get {
                return ResourceManager.GetString("CloseEsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap control {
            get {
                object obj = ResourceManager.GetObject("control", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap control_record {
            get {
                object obj = ResourceManager.GetObject("control_record", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap control_record_yellow {
            get {
                object obj = ResourceManager.GetObject("control_record_yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap counter_reset {
            get {
                object obj = ResourceManager.GetObject("counter_reset", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 CRF: 的本地化字符串。
        /// </summary>
        internal static string CRF {
            get {
                return ResourceManager.GetString("CRF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cross {
            get {
                object obj = ResourceManager.GetObject("cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Crosshair {
            get {
                object obj = ResourceManager.GetObject("Crosshair", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cursor {
            get {
                object obj = ResourceManager.GetObject("cursor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Cut out effect size: 的本地化字符串。
        /// </summary>
        internal static string CutOutEffectSize {
            get {
                return ResourceManager.GetString("CutOutEffectSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cut out effect: 的本地化字符串。
        /// </summary>
        internal static string CutOutEffectType {
            get {
                return ResourceManager.GetString("CutOutEffectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap disk_black {
            get {
                object obj = ResourceManager.GetObject("disk_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap disks_black {
            get {
                object obj = ResourceManager.GetObject("disks_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap document_copy {
            get {
                object obj = ResourceManager.GetObject("document_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap drive_globe {
            get {
                object obj = ResourceManager.GetObject("drive_globe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Drop shadow color... 的本地化字符串。
        /// </summary>
        internal static string DropShadowColor {
            get {
                return ResourceManager.GetString("DropShadowColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duplicate 的本地化字符串。
        /// </summary>
        internal static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap edit_alignment {
            get {
                object obj = ResourceManager.GetObject("edit_alignment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap edit_alignment_center {
            get {
                object obj = ResourceManager.GetObject("edit_alignment_center", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap edit_alignment_center_white {
            get {
                object obj = ResourceManager.GetObject("edit_alignment_center_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap edit_alignment_right {
            get {
                object obj = ResourceManager.GetObject("edit_alignment_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap edit_alignment_right_white {
            get {
                object obj = ResourceManager.GetObject("edit_alignment_right_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap edit_alignment_white {
            get {
                object obj = ResourceManager.GetObject("edit_alignment_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap edit_bold {
            get {
                object obj = ResourceManager.GetObject("edit_bold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap edit_bold_white {
            get {
                object obj = ResourceManager.GetObject("edit_bold_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap edit_italic {
            get {
                object obj = ResourceManager.GetObject("edit_italic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap edit_italic_white {
            get {
                object obj = ResourceManager.GetObject("edit_italic_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap edit_outline {
            get {
                object obj = ResourceManager.GetObject("edit_outline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap edit_outline_white {
            get {
                object obj = ResourceManager.GetObject("edit_outline_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap edit_shade {
            get {
                object obj = ResourceManager.GetObject("edit_shade", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap edit_shade_white {
            get {
                object obj = ResourceManager.GetObject("edit_shade_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap edit_underline {
            get {
                object obj = ResourceManager.GetObject("edit_underline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap edit_underline_white {
            get {
                object obj = ResourceManager.GetObject("edit_underline_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap edit_vertical_alignment {
            get {
                object obj = ResourceManager.GetObject("edit_vertical_alignment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap edit_vertical_alignment_middle {
            get {
                object obj = ResourceManager.GetObject("edit_vertical_alignment_middle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap edit_vertical_alignment_middle_white {
            get {
                object obj = ResourceManager.GetObject("edit_vertical_alignment_middle_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap edit_vertical_alignment_top {
            get {
                object obj = ResourceManager.GetObject("edit_vertical_alignment_top", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap edit_vertical_alignment_top_white {
            get {
                object obj = ResourceManager.GetObject("edit_vertical_alignment_top_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap edit_vertical_alignment_white {
            get {
                object obj = ResourceManager.GetObject("edit_vertical_alignment_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Clipboard does not contain an image. 的本地化字符串。
        /// </summary>
        internal static string EditorStartupForm_ClipboardDoesNotContainAnImage {
            get {
                return ResourceManager.GetString("EditorStartupForm_ClipboardDoesNotContainAnImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap eraser {
            get {
                object obj = ResourceManager.GetObject("eraser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap exclamation_button {
            get {
                object obj = ResourceManager.GetObject("exclamation_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Browse for ffmpeg.exe 的本地化字符串。
        /// </summary>
        internal static string FFmpegOptionsForm_buttonFFmpegBrowse_Click_Browse_for_ffmpeg_exe {
            get {
                return ResourceManager.GetString("FFmpegOptionsForm_buttonFFmpegBrowse_Click_Browse_for_ffmpeg_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bitrate: {0}k 的本地化字符串。
        /// </summary>
        internal static string FFmpegOptionsForm_UpdateUI_Bitrate___0_k {
            get {
                return ResourceManager.GetString("FFmpegOptionsForm_UpdateUI_Bitrate___0_k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quality: 的本地化字符串。
        /// </summary>
        internal static string FFmpegOptionsForm_UpdateUI_Quality_ {
            get {
                return ResourceManager.GetString("FFmpegOptionsForm_UpdateUI_Quality_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap folder_open_image {
            get {
                object obj = ResourceManager.GetObject("folder_open_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 FPS limit: 的本地化字符串。
        /// </summary>
        internal static string FPSLimit {
            get {
                return ResourceManager.GetString("FPSLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap gear {
            get {
                object obj = ResourceManager.GetObject("gear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap gradient {
            get {
                object obj = ResourceManager.GetObject("gradient", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap grid {
            get {
                object obj = ResourceManager.GetObject("grid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap grid_white {
            get {
                object obj = ResourceManager.GetObject("grid_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Highlight 的本地化字符串。
        /// </summary>
        internal static string Highlight {
            get {
                return ResourceManager.GetString("Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap highlighter_text {
            get {
                object obj = ResourceManager.GetObject("highlighter_text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap image__pencil {
            get {
                object obj = ResourceManager.GetObject("image__pencil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap image__plus {
            get {
                object obj = ResourceManager.GetObject("image__plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap image_crop {
            get {
                object obj = ResourceManager.GetObject("image_crop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap image_empty {
            get {
                object obj = ResourceManager.GetObject("image_empty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap image_resize {
            get {
                object obj = ResourceManager.GetObject("image_resize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap image_resize_actual {
            get {
                object obj = ResourceManager.GetObject("image_resize_actual", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap image_saturation {
            get {
                object obj = ResourceManager.GetObject("image_saturation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap image_select {
            get {
                object obj = ResourceManager.GetObject("image_select", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Image copied 的本地化字符串。
        /// </summary>
        internal static string ImageCopied {
            get {
                return ResourceManager.GetString("ImageCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add image effects... 的本地化字符串。
        /// </summary>
        internal static string ImageEffects {
            get {
                return ResourceManager.GetString("ImageEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image saved 的本地化字符串。
        /// </summary>
        internal static string ImageSaved {
            get {
                return ResourceManager.GetString("ImageSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image saved 的本地化字符串。
        /// </summary>
        internal static string ImageSavedAs {
            get {
                return ResourceManager.GetString("ImageSavedAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image uploading 的本地化字符串。
        /// </summary>
        internal static string ImageUploading {
            get {
                return ResourceManager.GetString("ImageUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap keyboard_enter {
            get {
                object obj = ResourceManager.GetObject("keyboard-enter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap layer {
            get {
                object obj = ResourceManager.GetObject("layer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap layer__minus {
            get {
                object obj = ResourceManager.GetObject("layer__minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap layer__pencil {
            get {
                object obj = ResourceManager.GetObject("layer__pencil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap layer_flip {
            get {
                object obj = ResourceManager.GetObject("layer_flip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap layer_flip_vertical {
            get {
                object obj = ResourceManager.GetObject("layer_flip_vertical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap layer_fullscreen {
            get {
                object obj = ResourceManager.GetObject("layer_fullscreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap layer_shade {
            get {
                object obj = ResourceManager.GetObject("layer_shade", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap layer_shade_white {
            get {
                object obj = ResourceManager.GetObject("layer_shade_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap layer_shape {
            get {
                object obj = ResourceManager.GetObject("layer_shape", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap layer_shape_arrow {
            get {
                object obj = ResourceManager.GetObject("layer_shape_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap layer_shape_arrow_white {
            get {
                object obj = ResourceManager.GetObject("layer_shape_arrow_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap layer_shape_ellipse {
            get {
                object obj = ResourceManager.GetObject("layer_shape_ellipse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap layer_shape_ellipse_region {
            get {
                object obj = ResourceManager.GetObject("layer_shape_ellipse_region", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap layer_shape_line {
            get {
                object obj = ResourceManager.GetObject("layer_shape_line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap layer_shape_line_white {
            get {
                object obj = ResourceManager.GetObject("layer_shape_line_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap layer_shape_polygon {
            get {
                object obj = ResourceManager.GetObject("layer_shape_polygon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap layer_shape_region {
            get {
                object obj = ResourceManager.GetObject("layer_shape_region", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap layer_shape_round {
            get {
                object obj = ResourceManager.GetObject("layer_shape_round", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap layer_shape_round_region {
            get {
                object obj = ResourceManager.GetObject("layer_shape_round_region", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap layer_shape_text {
            get {
                object obj = ResourceManager.GetObject("layer_shape_text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap layers {
            get {
                object obj = ResourceManager.GetObject("layers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap layers_arrange {
            get {
                object obj = ResourceManager.GetObject("layers_arrange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap layers_arrange_back {
            get {
                object obj = ResourceManager.GetObject("layers_arrange_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap layers_stack_arrange {
            get {
                object obj = ResourceManager.GetObject("layers_stack_arrange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap layers_stack_arrange_back {
            get {
                object obj = ResourceManager.GetObject("layers_stack_arrange_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap layout_center {
            get {
                object obj = ResourceManager.GetObject("layout_center", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap layout_split {
            get {
                object obj = ResourceManager.GetObject("layout_split", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap layout_split_vertical {
            get {
                object obj = ResourceManager.GetObject("layout_split_vertical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Use light resize nodes 的本地化字符串。
        /// </summary>
        internal static string LightResizeNodes {
            get {
                return ResourceManager.GetString("LightResizeNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lock menu 的本地化字符串。
        /// </summary>
        internal static string LockMenu {
            get {
                return ResourceManager.GetString("LockMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap magnifier_zoom {
            get {
                object obj = ResourceManager.GetObject("magnifier_zoom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Magnify strength: 的本地化字符串。
        /// </summary>
        internal static string MagnifyStrength {
            get {
                return ResourceManager.GetString("MagnifyStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu icon size: 的本地化字符串。
        /// </summary>
        internal static string MenuIconSize {
            get {
                return ResourceManager.GetString("MenuIconSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap monitor {
            get {
                object obj = ResourceManager.GetObject("monitor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap monitor_image {
            get {
                object obj = ResourceManager.GetObject("monitor_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap monitor_window {
            get {
                object obj = ResourceManager.GetObject("monitor_window", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 New line: Ctrl + Enter, OK: Enter 的本地化字符串。
        /// </summary>
        internal static string NewLineCtrlEnterOKEnter {
            get {
                return ResourceManager.GetString("NewLineCtrlEnterOKEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New line: Enter, OK: Ctrl + Enter 的本地化字符串。
        /// </summary>
        internal static string NewLineEnterOKCtrlEnter {
            get {
                return ResourceManager.GetString("NewLineEnterOKCtrlEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] openhand {
            get {
                object obj = ResourceManager.GetObject("openhand", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Open keybinds web page... 的本地化字符串。
        /// </summary>
        internal static string OpenKeybindsPage {
            get {
                return ResourceManager.GetString("OpenKeybindsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停 的本地化字符串。
        /// </summary>
        internal static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap pencil {
            get {
                object obj = ResourceManager.GetObject("pencil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap pencil__arrow {
            get {
                object obj = ResourceManager.GetObject("pencil__arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 像素 的本地化字符串。
        /// </summary>
        internal static string Pixelate {
            get {
                return ResourceManager.GetString("Pixelate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap printer {
            get {
                object obj = ResourceManager.GetObject("printer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 处理 的本地化字符串。
        /// </summary>
        internal static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rectangle capture light 的本地化字符串。
        /// </summary>
        internal static string RectangleLight_InitializeComponent_Rectangle_capture_light {
            get {
                return ResourceManager.GetString("RectangleLight_InitializeComponent_Rectangle_capture_light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 X: {0} Y: {1} W: {2} H: {3} 的本地化字符串。
        /// </summary>
        internal static string RectangleRegion_GetAreaText_Area {
            get {
                return ResourceManager.GetString("RectangleRegion_GetAreaText_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RGB: {0}, {1}, {2}
        ///Hex: {3}
        ///X: {4} Y: {5} 的本地化字符串。
        /// </summary>
        internal static string RectangleRegion_GetColorPickerText {
            get {
                return ResourceManager.GetString("RectangleRegion_GetColorPickerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rectangle capture transparent 的本地化字符串。
        /// </summary>
        internal static string RectangleTransparent_RectangleTransparent_Rectangle_capture_transparent {
            get {
                return ResourceManager.GetString("RectangleTransparent_RectangleTransparent_Rectangle_capture_transparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image editor 的本地化字符串。
        /// </summary>
        internal static string RegionCaptureForm_InitializeComponent_ImageEditor {
            get {
                return ResourceManager.GetString("RegionCaptureForm_InitializeComponent_ImageEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShareX - Image editor 的本地化字符串。
        /// </summary>
        internal static string RegionCaptureForm_ShowExitConfirmation_ShareXImageEditor {
            get {
                return ResourceManager.GetString("RegionCaptureForm_ShowExitConfirmation_ShareXImageEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are unsaved changes.
        ///Would you like to close image editor? 的本地化字符串。
        /// </summary>
        internal static string RegionCaptureForm_ShowExitConfirmation_Text {
            get {
                return ResourceManager.GetString("RegionCaptureForm_ShowExitConfirmation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tip: You can pan image by holding mouse middle button and dragging. 的本地化字符串。
        /// </summary>
        internal static string RegionCaptureForm_TipYouCanPanImageByHoldingMouseMiddleButtonAndDragging {
            get {
                return ResourceManager.GetString("RegionCaptureForm_TipYouCanPanImageByHoldingMouseMiddleButtonAndDragging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 继续 的本地化字符串。
        /// </summary>
        internal static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to abort this recording? 的本地化字符串。
        /// </summary>
        internal static string ScreenRecordForm_ConfirmCancel {
            get {
                return ResourceManager.GetString("ScreenRecordForm_ConfirmCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        internal static string ScreenRecordForm_Start {
            get {
                return ResourceManager.GetString("ScreenRecordForm_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to start recording. 的本地化字符串。
        /// </summary>
        internal static string ScreenRecordForm_StartRecording_Click_tray_icon_to_start_recording_ {
            get {
                return ResourceManager.GetString("ScreenRecordForm_StartRecording_Click_tray_icon_to_start_recording_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to stop recording. 的本地化字符串。
        /// </summary>
        internal static string ScreenRecordForm_StartRecording_Click_tray_icon_to_stop_recording_ {
            get {
                return ResourceManager.GetString("ScreenRecordForm_StartRecording_Click_tray_icon_to_stop_recording_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Encoding... 的本地化字符串。
        /// </summary>
        internal static string ScreenRecordForm_StartRecording_Encoding___ {
            get {
                return ResourceManager.GetString("ScreenRecordForm_StartRecording_Encoding___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waiting... 的本地化字符串。
        /// </summary>
        internal static string ScreenRecordForm_StartRecording_Waiting___ {
            get {
                return ResourceManager.GetString("ScreenRecordForm_StartRecording_Waiting___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        internal static string ScreenRecordForm_Stop {
            get {
                return ResourceManager.GetString("ScreenRecordForm_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop capture 的本地化字符串。
        /// </summary>
        internal static string ScrollingCaptureForm_StartCapture_Stop_capture {
            get {
                return ResourceManager.GetString("ScrollingCaptureForm_StartCapture_Stop_capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start capture 的本地化字符串。
        /// </summary>
        internal static string ScrollingCaptureForm_StopCapture_Start_capture {
            get {
                return ResourceManager.GetString("ScrollingCaptureForm_StopCapture_Start_capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Arrow head direction: 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_ArrowHeadDirection {
            get {
                return ResourceManager.GetString("ShapeManager_ArrowHeadDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Border style: 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_BorderStyle {
            get {
                return ResourceManager.GetString("ShapeManager_BorderStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center points: 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CenterPoints {
            get {
                return ResourceManager.GetString("ShapeManager_CenterPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blur strength: 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Blur_radius_ {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Blur_radius_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Border color... 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Border_color___ {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Border_color___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Border size: 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Border_size_ {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Border_size_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Capture 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Capture {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Capture active monitor 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Capture_active_monitor {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Capture_active_monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Capture fullscreen 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Capture_fullscreen {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Capture_fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Capture monitor 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Capture_monitor {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Capture_monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Corner radius: 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Corner_radius_ {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Corner_radius_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable animations 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_EnableAnimations {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_EnableAnimations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fill color... 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Fill_color___ {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Fill_color___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fixed size region mode 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Fixed_size_region_mode {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Fixed_size_region_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Height: 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Height_ {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Height_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Highlight color... 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Highlight_color___ {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Highlight_color___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Magnifier pixel count: 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Magnifier_pixel_count_ {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Magnifier_pixel_count_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Magnifier pixel size: 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Magnifier_pixel_size_ {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Magnifier_pixel_size_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multi region mode 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Multi_region_mode {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Multi_region_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Options {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pixel size: 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Pixel_size_ {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Pixel_size_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remember menu state 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_RememberMenuState {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_RememberMenuState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show FPS 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Show_FPS {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Show_FPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show magnifier 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Show_magnifier {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Show_magnifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show position and size info 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Show_position_and_size_info {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Show_position_and_size_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show screen wide crosshair 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Show_screen_wide_crosshair {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Show_screen_wide_crosshair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Square shape magnifier 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Square_shape_magnifier {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Square_shape_magnifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch to drawing tool after shape selection 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_SwitchToDrawingToolAfterSelection {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_SwitchToDrawingToolAfterSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch to selection tool after shape drawing 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_SwitchToSelectionToolAfterDrawing {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_SwitchToSelectionToolAfterDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Width: 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateContextMenu_Width_ {
            get {
                return ResourceManager.GetString("ShapeManager_CreateContextMenu_Width_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Editor menu 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_AnnotateMenu {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_AnnotateMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply changes &amp; continue task (Enter) 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_ApplyChangesContinueTaskEnter {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_ApplyChangesContinueTaskEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto close editor on task 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_AutoCloseEditorOnTask {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_AutoCloseEditorOnTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto crop image... 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_AutoCropImage {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_AutoCropImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bring forward 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_BringForward {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_BringForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bring to front 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_BringToFront {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_BringToFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel task (Esc) 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_CancelTaskEsc {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_CancelTaskEsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Canvas size... 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_CanvasSize {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_CanvasSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Capture regions 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_CaptureRegions {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_CaptureRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Continue task (Space or right click) 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_ContinueTaskSpaceOrRightClick {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_ContinueTaskSpaceOrRightClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy image to clipboard (Ctrl + Shift + C) 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_CopyImageToClipboard {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_CopyImageToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Crop image... 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_CropImage {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_CropImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_Delete {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete all 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_DeleteAll {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drop shadow 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_DropShadow {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_DropShadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_Edit {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Editor start mode: 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_EditorStartMode {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_EditorStartMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flip horizontal 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_FlipHorizontal {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_FlipHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flip vertical 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_FlipVertical {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_FlipVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font size: 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_FontSize {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_Image {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image size... 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_ImageSize {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_ImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert image file... 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_InsertImageFile {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_InsertImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert image from screen... 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_InsertImageFromScreen {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_InsertImageFromScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interpolation mode: 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_InterpolationMode {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_InterpolationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Capture last region 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_LastRegion {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_LastRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New image... 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_NewImage {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_NewImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open image file... 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_OpenImageFile {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_OpenImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste image/text 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_PasteImageText {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_PasteImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print image... (Ctrl + P) 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_PrintImage {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_PrintImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rotate 180° 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_Rotate180 {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_Rotate180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rotate 90° clockwise 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_Rotate90Clockwise {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_Rotate90Clockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rotate 90° counter clockwise 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_Rotate90CounterClockwise {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_Rotate90CounterClockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run after capture tasks (Enter) 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_RunAfterCaptureTasks {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_RunAfterCaptureTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save image (Ctrl + S) 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_SaveImage {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_SaveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save image as... (Ctrl + Shift + S) 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_SaveImageAs {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_SaveImageAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send backward 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_SendBackward {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_SendBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send to back 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_SendToBack {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_SendToBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value of first step: 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_StartingStepValue {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_StartingStepValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step type: 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_StepType {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_StepType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tool options 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_ToolOptions {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_ToolOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Undo 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_Undo {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload image (Ctrl + U) 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_UploadImage {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_UploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom to fit on open 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CreateToolbar_ZoomToFitOnOpen {
            get {
                return ResourceManager.GetString("ShapeManager_CreateToolbar_ZoomToFitOnOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cursor type: 的本地化字符串。
        /// </summary>
        internal static string ShapeManager_CursorType {
            get {
                return ResourceManager.GetString("ShapeManager_CursorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap smiley_cool {
            get {
                object obj = ResourceManager.GetObject("smiley_cool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap smiley_yell {
            get {
                object obj = ResourceManager.GetObject("smiley_yell", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap stamp_cursor {
            get {
                object obj = ResourceManager.GetObject("stamp_cursor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap table_delete_column {
            get {
                object obj = ResourceManager.GetObject("table_delete_column", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap test_32 {
            get {
                object obj = ResourceManager.GetObject("test_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 This window will close before opening the keybinds web page. Do you want to continue? 的本地化字符串。
        /// </summary>
        internal static string ThisWindowWillCloseBeforeOpeningKeybindsPageWantContinue {
            get {
                return ResourceManager.GetString("ThisWindowWillCloseBeforeOpeningKeybindsPageWantContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap tick {
            get {
                object obj = ResourceManager.GetObject("tick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Capture 的本地化字符串。
        /// </summary>
        internal static string WebpageCaptureForm_UpdateControls_Capture {
            get {
                return ResourceManager.GetString("WebpageCaptureForm_UpdateControls_Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        internal static string WebpageCaptureForm_UpdateControls_Stop {
            get {
                return ResourceManager.GetString("WebpageCaptureForm_UpdateControls_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap wrench_screwdriver {
            get {
                object obj = ResourceManager.GetObject("wrench_screwdriver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
